#!/usr/bin/env node
/**
 * Cloudflare D1 Database Backup Script
 * Экспортирует данные из D1 в SQL dump
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const execAsync = promisify(exec);
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Конфигурация
const CONFIG = {
  databaseName: 'productlabelerpro',
  databaseId: '6bcefdbd-4109-4545-b521-d42694b7144c',
  backupDir: path.join(__dirname, '../backups'),
  retentionDays: 30, // Хранить бэкапы 30 дней
};

/**
 * Создать директорию для бэкапов
 */
async function ensureBackupDir() {
  try {
    await fs.access(CONFIG.backupDir);
  } catch {
    await fs.mkdir(CONFIG.backupDir, { recursive: true });
    console.log(`✅ Создана директория для бэкапов: ${CONFIG.backupDir}`);
  }
}

/**
 * Получить список всех таблиц
 */
async function getTables() {
  try {
    const { stdout } = await execAsync(
      `npx wrangler d1 execute ${CONFIG.databaseName} --command "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"`
    );
    
    // Парсинг вывода wrangler (JSON формат)
    const lines = stdout.split('\n').filter(line => line.trim());
    const tables = [];
    
    for (const line of lines) {
      try {
        const parsed = JSON.parse(line);
        if (parsed.name && !parsed.name.startsWith('sqlite_') && !parsed.name.startsWith('d1_')) {
          tables.push(parsed.name);
        }
      } catch {
        // Игнорируем строки, которые не JSON
      }
    }
    
    return tables;
  } catch (error) {
    console.error('❌ Ошибка получения списка таблиц:', error.message);
    return [];
  }
}

/**
 * Экспортировать данные таблицы
 */
async function exportTable(tableName) {
  try {
    const { stdout } = await execAsync(
      `npx wrangler d1 execute ${CONFIG.databaseName} --command "SELECT * FROM ${tableName}"`
    );
    
    // Парсинг данных
    const lines = stdout.split('\n').filter(line => line.trim());
    const rows = [];
    
    for (const line of lines) {
      try {
        rows.push(JSON.parse(line));
      } catch {
        // Игнорируем не-JSON строки
      }
    }
    
    return rows;
  } catch (error) {
    console.error(`❌ Ошибка экспорта таблицы ${tableName}:`, error.message);
    return [];
  }
}

/**
 * Генерировать SQL INSERT из данных
 */
function generateInserts(tableName, rows) {
  if (rows.length === 0) return '';
  
  const inserts = [];
  
  for (const row of rows) {
    const columns = Object.keys(row);
    const values = columns.map(col => {
      const val = row[col];
      if (val === null) return 'NULL';
      if (typeof val === 'string') return `'${val.replace(/'/g, "''")}'`;
      return val;
    });
    
    inserts.push(
      `INSERT INTO ${tableName} (${columns.join(', ')}) VALUES (${values.join(', ')});`
    );
  }
  
  return inserts.join('\n');
}

/**
 * Создать полный SQL dump
 */
async function createBackup() {
  console.log('🚀 Начинаем создание бэкапа...\n');
  
  await ensureBackupDir();
  
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupFile = path.join(CONFIG.backupDir, `backup-${timestamp}.sql`);
  
  let sqlDump = `-- Cloudflare D1 Database Backup
-- Database: ${CONFIG.databaseName}
-- Date: ${new Date().toISOString()}
-- Generated by: backup-d1.mjs

SET FOREIGN_KEYS = 0;

`;
  
  // Получить список таблиц
  console.log('📋 Получение списка таблиц...');
  const tables = await getTables();
  
  if (tables.length === 0) {
    console.log('⚠️  Таблицы не найдены или ошибка подключения');
    return;
  }
  
  console.log(`✅ Найдено таблиц: ${tables.length}\n`);
  
  // Экспортировать каждую таблицу
  for (const table of tables) {
    console.log(`📦 Экспорт таблицы: ${table}...`);
    
    const rows = await exportTable(table);
    
    if (rows.length > 0) {
      sqlDump += `\n-- Table: ${table} (${rows.length} rows)\n`;
      sqlDump += `DELETE FROM ${table};\n`;
      sqlDump += generateInserts(table, rows);
      sqlDump += '\n\n';
      console.log(`   ✅ Экспортировано ${rows.length} записей`);
    } else {
      console.log(`   ⚠️  Таблица пуста`);
    }
  }
  
  sqlDump += '\nSET FOREIGN_KEYS = 1;\n';
  
  // Сохранить в файл
  await fs.writeFile(backupFile, sqlDump, 'utf-8');
  
  const stats = await fs.stat(backupFile);
  const sizeKB = (stats.size / 1024).toFixed(2);
  
  console.log(`\n✅ Бэкап создан успешно!`);
  console.log(`📁 Файл: ${backupFile}`);
  console.log(`📊 Размер: ${sizeKB} KB`);
  
  // Очистка старых бэкапов
  await cleanupOldBackups();
}

/**
 * Удалить старые бэкапы
 */
async function cleanupOldBackups() {
  try {
    const files = await fs.readdir(CONFIG.backupDir);
    const now = Date.now();
    const maxAge = CONFIG.retentionDays * 24 * 60 * 60 * 1000;
    
    let deleted = 0;
    
    for (const file of files) {
      if (!file.startsWith('backup-') || !file.endsWith('.sql')) continue;
      
      const filePath = path.join(CONFIG.backupDir, file);
      const stats = await fs.stat(filePath);
      const age = now - stats.mtimeMs;
      
      if (age > maxAge) {
        await fs.unlink(filePath);
        deleted++;
        console.log(`🗑️  Удалён старый бэкап: ${file}`);
      }
    }
    
    if (deleted > 0) {
      console.log(`\n🧹 Удалено старых бэкапов: ${deleted}`);
    }
  } catch (error) {
    console.error('⚠️  Ошибка очистки старых бэкапов:', error.message);
  }
}

/**
 * Восстановить из бэкапа
 */
async function restoreBackup(backupFile) {
  console.log(`🔄 Восстановление из бэкапа: ${backupFile}\n`);
  
  try {
    const sql = await fs.readFile(backupFile, 'utf-8');
    
    // Разбить на отдельные команды
    const commands = sql.split(';').filter(cmd => cmd.trim() && !cmd.trim().startsWith('--'));
    
    console.log(`📝 Найдено команд: ${commands.length}`);
    
    for (let i = 0; i < commands.length; i++) {
      const cmd = commands[i].trim();
      if (!cmd) continue;
      
      try {
        await execAsync(
          `npx wrangler d1 execute ${CONFIG.databaseName} --command "${cmd.replace(/"/g, '\\"')}"`
        );
        
        if ((i + 1) % 10 === 0) {
          console.log(`   ✅ Выполнено ${i + 1}/${commands.length} команд...`);
        }
      } catch (error) {
        console.error(`   ❌ Ошибка выполнения команды ${i + 1}:`, error.message);
      }
    }
    
    console.log('\n✅ Восстановление завершено!');
  } catch (error) {
    console.error('❌ Ошибка восстановления:', error.message);
  }
}

// CLI
const args = process.argv.slice(2);
const command = args[0];

if (command === 'restore' && args[1]) {
  restoreBackup(args[1]);
} else if (command === 'restore') {
  console.error('❌ Укажите файл для восстановления: npm run backup:restore <file>');
} else {
  createBackup();
}
